### ISSUE TITLE
Windows SmartScreen

### ISSUE THREAD

**Issue by anhduy82** [roldanjr/pomatez#118]
Windows SmartScreen reports that the file is unsafe when I try to run the exe file. Is the program really dangerous or it is just a false positive? I stared your project and I think this will be a good program to use in to improve productivity. Please help.

**Comment by roldanjr** [comment]
No, the program is not dangerous.

It happened because the app  is unsigned. You can find out more by researching code-signing for Apple and Microsoft.

But just to inform you that It is 100% safe. Just run it anyway.

**Comment by anhduy82** [comment]
Thanks
