### ISSUE TITLE
Bug Report: full screen break doesn't do anything on ubuntu

### ISSUE THREAD

**Issue by tonytvo** [roldanjr/pomatez#119]
**Describe the bug**
full screen break doesn't do anything on ubuntu

**To Reproduce**
select full-screen break on ubuntu 20.04

1. Go to 'Settings'
2. Click on 'Fullscreen break'

**Expected behavior**
- Prevent users from doing anything with the computer

**Screenshots**

**Desktop (please complete the following information):**

- OS: ubuntu 20.04
- App Version 1.0.0

**Additional context**

**Comment by roldanjr** [comment]
Hello @tonytvo , 

May I know if what package you do installed on your machine? .deb or snap?

**Comment by tonytvo** [comment]
it is snap

**Comment by roldanjr** [comment]
Thank you for the response. I don't actually know why it happened on your machine. 

I used Manjaro and it works perfectly fined to me and there are lots of Ubuntu 20.04 users too but you are the one that I know that experience that bug. 

I will try to figure it out as soon as I can @tonytvo . I'm really sorry.

**Comment by roldanjr** [comment]
I just installed Ubuntu and I can confirm that it doesn't really work. Thanks for informing me @tonytvo . 

I will try to figure out how to fix this problem as soon as I can.

**Comment by roldanjr** [comment]
@tonytvo I already fixed this bug and released new version of the app. 

If this update did fixed the problem please close this issue. 

Thanks and have a nice day!

**Comment by tonytvo** [comment]
@roldanjr, the latest updates does seem to fix the problem for me on Ubuntu
