### ISSUE TITLE
Idle Detection

### ISSUE THREAD

**Issue by easpro** [roldanjr/pomatez#120]
Feature suggestion:  When computer is idle, break timer will pause.  Break timer countdown will resume when mouse or keyboard activity is detected by the software. 

Example:  If a user does not use the computer for 30 seconds, the break timer will pause.  This is useful if a user leaves their desk or goes to lunch.  Computer will not be on break when user returns to their desk.  User will not be locked out of their computer if using Strict Mode.

Windows 10
Pometez v1.0.0
Windows Installer

**Comment by roldanjr** [comment]
**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- App Version [e.g. 22]
- Installer Type [e.g Windows Installer]

**Additional context**
Add any other context about the problem here.
