### ISSUE TITLE
Simplify Tasks, increase focus (no cards, allow hide description)

### ISSUE THREAD

**Issue by peachp** [roldanjr/pomatez#144]
For me, this app is not to replace my main tasks system else where.
I got confused how the Task list works, why there are listS, some cards etc. Not sure why a Task is called "Card"...

1.
The way I see it, in this app I would put only a handful tasks for one - three days, which I want to focus on.
So maybe just a super simple list of tasks:
Task 1
Task 2
[Empty field: input new task]

That's it! Maybe allow to re-arrange the tasks, so the top one is shown under "Timer".

2.
Also, for the same reasons I would either completely remove descriptions, or at least have a Setting to hide them under "Timer". Again, I'm not using Pomatez as my project management tool where I have detailed description of tasks.
I use Pomatez to keep me focus what I should be working on - so I can quickly glance on it (it is always on top for me) to immediately see what I should be focusing on, and not read some descriptions.

3. I would also display the Task I'm focusing on under Timer, in a more prominent way: just the Task itself (w/o description, see 2.), bigger and centered horizontally and vertically between "Stay Focused" and the pause button. Or something like that.

**Comment by roldanjr** [comment]
I will admit that this app is not yet polish due to some reasons.  
A lot of things need to refactor and improve, but I will try to improve this app as soon as I have enough time.
Anyways, thank you @peachp.

**Comment by peachp** [comment]
Sounds good!
The UX is a subjective topic, so it is just my view. When you come to this area, let me know and I can provide more detailed spec of how I think a good UX should be.

For now, as a quick fix it would be great to at least hide the "There's no description..." message under Time under the Task (Card?) title. This is something I believe would fit everyone. It will reduce the visual noise on Time tab and allow to stay focused more.
