### ISSUE TITLE
Bug Report: Flickering Timer Bar

### ISSUE THREAD

**Issue by devtayls** [roldanjr/pomatez#155]
**Describe the bug**

The timer bar element is flickering when the mouse hovers over the timer tab controls.

**To Reproduce**

1. Open the Pomatez app, starting a new session
2. Go to 'the Timer' tab
3. Before starting the timer / with a full timer bar.
4. Hover mouse over play, restart, forward, volume or sessions clickable elements. 
5. The timer bar element will exhibit visual distortion / flickering behavior.

**Expected behavior**

- The timer bar should remain static so long as the timer has not started.
- The timer bar should not be missing arbitrary sections. 

**Screenshots**

![flickering_timer_bar](https://user-images.githubusercontent.com/16793430/111879998-7d81d280-896e-11eb-9741-08cd11dd4280.png)

**Desktop (please complete the following information):**

- OS: Linux (Ubuntu)
- App Version 20.04
- Installer Used Ubuntu repository / apt installer

**Comment by roldanjr** [comment]
I guess this bug is already fixed with the latest release, so I will close this ticket for now but still feel free to open it again if the bug persists.
