### ISSUE TITLE
Always need to force quit in order to close the app

### ISSUE THREAD

**Issue by jaygal0** [roldanjr/pomatez#185]
The app is great. The only issue that I run into is that when I want to quit the app I'm unable to do so, this prevents me from logging out of my account.

**Comment by sekwah41** [comment]
Hey @jaygal0 can you just confirm for me if both close to tray and minimize to tray is disabled?
![image](https://user-images.githubusercontent.com/3209834/155821714-a683de7b-ce91-4a94-8e84-e68fb7a52124.png)

By default close to tray is on.

**Comment by jaygal0** [comment]
Hey @sekwah41 I appreciate you getting back to me, but unfortunately I've uninstalled the app.

Keep up the good work 👍

**Comment by sekwah41** [comment]
Ahh to problem. I'll close this for now and see if it pops back up.

**Comment by kruschid** [comment]
@sekwah41

Confirming that disabling the "Close To Tray" option resolves the problem, while the "Minimize To Tray" setting is irrelevant in this scenario.

[1.2.2](https://github.com/roldanjr/pomatez/compare/v1.2.1...v1.2.2) (2022-12-21)  @ MBPro M1 Max Ventrua 13.2.1
