### ISSUE TITLE
Bug Report: Can't run on macOS: “Pomatez” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by darthwalsh** [roldanjr/pomatez#200]
**Describe the bug**
After install, I get this error:
> “Pomatez” cannot be opened because the developer cannot be verified.
> macOS cannot verify that this app is free from malware.

**To Reproduce**
Installed pomatez from brew, got this problem. Trashed that, downloaded [DMG from github release](https://github.com/roldanjr/pomatez/releases/download/v1.1.0/Pomatez-v1.1.0-mac.dmg), got the same thing

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2829438/154578364-3d9491b7-524c-4347-8a34-8da8688204d6.png)

**Desktop (please complete the following information):**

- OS: macOS 12.1
- App Version v1.1.0
- Installer Used: tried both `releases/download/v1.1.0/Pomatez-v1.1.0-mac.dmg` and `brew install --cask pomatez` which seem to do the same thing.

**Additional context**
Does the app need to be signed? I'm guessing there's a way to hack my system or self-sign the app or something, but that shouldn't be required?

**Comment by AugustasV** [comment]
Hi, workaround is to go Applications, hold ctrl and double click the application, than you will see same dialog but with option to Open. 
For developer to get rid of that issue he have to buy Apple Developer license, who doesn't make sense while using open source software.

**Comment by sekwah41** [comment]
For this to be properly supported we would need to have and pay for a developer license.

We just don't have any licenses we can use for this project atm. Though I may take a look at getting one in the future for some of my other projects so I will return to this and chat with @roldanjr at that point.

**Comment by roldanjr** [comment]
Yes, I agree with @sekwah41 . For now, it is not reasonable to buy a license for this small project.

What you can do ATM is what @AugustasV has said if you really want to try this app on your machine.

**Comment by sekwah41** [comment]
Closing this issue as it's not something we can really do for now. Though we may want to create a guide on troubleshooting if more people start to encounter this.
