### ISSUE TITLE
Pomatez will not run on osx 10.15.3

### ISSUE THREAD

**Issue by gozes** [roldanjr/pomatez#239]
So just installed by brew but when I tried to run it get the below message. I tried the official insaller as well from https://roldanjr.github.io/pomatez/ but no luck 
“Pomatez” cannot be opened because the developer cannot be verified.

**Comment by sekwah41** [comment]
https://support.apple.com/en-gb/guide/mac-help/mh40616/mac#:~:text=Control%2Dclick%20the%20app%20icon,you%20can%20any%20registered%20app.

This is not an error, we just don't have the funds to pay for code signing as this is an open source project and you need an apple developer license to sign software.

You need to bypass this on osc
