### ISSUE TITLE
Can you cut a new release with the new compact mode (or is the master branch not ready to be released?)

### ISSUE THREAD

**Issue by kwand** [roldanjr/pomatez#243]
As titled.

**Comment by sekwah41** [comment]
I need to set up the automated release uploading to github as that's how most people get their versions though I believe I can sort that out manually for the files tbh. Ill take a look in a bit.

**Comment by q-wertz** [comment]
Are there any news on that? There seems to be a tag but no release and also on the website there are still only the old builds...

**Comment by sekwah41** [comment]
There are some issues on the current branch. As the rust version will take longer to do I will spend some time fixing the bugs with the electron one for fullscreen mode which is blocking its release.

**Comment by sekwah41** [comment]
Had some nasty internet issues which delayed plans today. Will see if I get time tomorrow but it will likely be on the weekend instead.

**Comment by sekwah41** [comment]
Sorry for the delays. I have had a lot with work and other projects though spent the last half an hour making a load of UI tweaks to just fully enable resizing of the window.

There was some odd logic behind it being resizeable or not and toggling that which would sometimes break on different operating systems. But a fix on one OS seemed to break it on another. Altering the CSS to allow it to resize seemed the most logical option but I just haven't had the time to sit down properly as things would keep popping up.

**Comment by gillisandrew** [comment]
@sekwah41 what's blocking the release pipeline exactly? Can we put out an alpha or beta release?

FYI unauthenticated users can download those build artifacts.

**Comment by sekwah41** [comment]
Ah yea fair point. The resize stuff is blocking release. Though we almost have that finished to a releasable stage.

**Comment by roldanjr** [comment]
I'll close this ticket now since the compact mode is already included in the latest release.
