### ISSUE TITLE
Bug Report: Cannot open V1.2 on Windows 11

### ISSUE THREAD

**Issue by weeshinwang** [roldanjr/pomatez#246]
Cannot open V1.2 on Windows 11, it seems like something goes wrong with importing `uuid` pacakge.

![Snipaste_2022-04-14_08-57-01](https://user-images.githubusercontent.com/14191453/163293498-ab289742-fd05-4a6a-8875-d5e802def35f.jpg)

**Comment by caeyo** [comment]
Also have been receiving the same error on Windows 10 since attempting to update, so it's not an isolated issue nor one exclusive to Windows 11.

**Comment by sekwah41** [comment]
Yea i could have sworn id tested the releases it built but something thats changed since I last tested is also causing this on the AppImage versions.

**Comment by sekwah41** [comment]
Upon investigation, it seems it was bumping the electron version which caused this. I will test tomorrow and perform another release.

**Comment by sekwah41** [comment]
Ive bumped electron up to 18 and lowered the uuid library version, which was causing this issue.

**Comment by sekwah41** [comment]
@weeshinwang @caeyo can you give this a try on windows? https://github.com/roldanjr/pomatez/actions/runs/2217418376

**Comment by weeshinwang** [comment]
> @weeshinwang @caeyo can you give this a try on windows? https://github.com/roldanjr/pomatez/actions/runs/2217418376

No errors this time 😊

**Comment by sekwah41** [comment]
Once I get one thing checked with @roldanjr i will merge and publish this version tomorrow :)
