### ISSUE TITLE
Floating window that shows the time left and task?

### ISSUE THREAD

**Issue by 2ndMessiah** [roldanjr/pomatez#265]
**Is your feature request related to a problem? Please describe.**

Thumb up for the app! It's pure with simplicity.

I wish there was a function to generate a small floating window during the Pomodoro session, where the remaining time and the task title are shown, and the windows could be set on top.

I think this could replace the 'always on top' option,  and showing the full-sized app UI would be a little bit of space waste IMO. 

Appreciate the excellent work!!

**Describe the solution you'd like**
NULL
**Describe alternatives you've considered**
NULL
**Additional context**
NULL

**Comment by dinesh-58** [comment]
Toggl Track's [mini timer](https://windows-cdn.softpedia.com/screenshots/Toggl-Desktop_11.png) does this well if you need a point of reference.

**Comment by 2ndMessiah** [comment]
Oh my goodness.....! I Appreciate it so much!
I've never known such a professional tool that could even be integrated
into notion and other workspace programs!!


dinesh-58 ***@***.***> 于2022年7月2日周六 13:02写道：

**Comment by 2ndMessiah** [comment]
It perfectly fits my requirement. TY so much.
Any other GTD or efficient software combo to recommend here? Would like to hear your comment!

**Comment by 2ndMessiah** [comment]
> Toggl Track's [mini timer](https://windows-cdn.softpedia.com/screenshots/Toggl-Desktop_11.png) does this well if you need a point of reference.

It perfectly fits my requirement. TY so much.
Any other GTD or efficient software combo to recommend here? Would like to hear your comment!

**Comment by dinesh-58** [comment]
Not really. This and Notion are all I use. Glad it helps though
