### ISSUE TITLE
Pomatez Cannot Be Opened Because the Developer Cannot be Verified

### ISSUE THREAD

**Issue by vyguera** [roldanjr/pomatez#266]
Recently I downloaded Pomatez to my Mac M1 and after installing and trying to open, the launcher says 'Pomatez Cannot Be Opened Because the Developer Cannot be Verified'

A workaround is is to open Finder, look for the app in Application folder and open it with right click -> open -> open anyway

It llooks like the signing certificate for mac versions needs an update.

- OS: MacOS Monterey v12.3.1 - Apple M1 Pro
- App Version 1.1.0
- Installer Used: DMG

**Comment by sekwah41** [comment]
#239 we do not have developer licenses as they are paid and this is an open source project
