### ISSUE TITLE
Add to Homebrew (cask)

### ISSUE THREAD

**Issue by moltar** [roldanjr/pomatez#82]
**Is your feature request related to a problem? Please describe.**

Please add the app to Homebrew to be able to install via CLI.

**Describe the solution you'd like**

App to be installable via Homebrew.

**Describe alternatives you've considered**

Installing manually.

**Additional context**

macOS

**Comment by roldanjrCodeArts9711** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Please add the app to Homebrew to be able to install via CLI.
> 
> **Describe the solution you'd like**
> 
> App to be installable via Homebrew.
> 
> **Describe alternatives you've considered**
> 
> Installing manually.
> 
> **Additional context**
> 
> macOS

I don't have MacOS but I will try to do that. Thanks @moltar .

**Comment by roldanjrCodeArts9711** [comment]
@moltar can you help with this if you don't mind?

**Comment by cabbage** [comment]
I created a PR for Homebrew Cask: https://github.com/Homebrew/homebrew-cask/pull/92480

See their [contritbution guide](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#getting-set-up-to-contribute) for updating it. 

You can just change the `version` and `sha256` in `Casks/pomatez.rb` and create a PR for future version updates.

**Comment by roldanjr** [comment]
Wow thank you so much @cabbage . 😃

**Comment by cabbage** [comment]
Any time.

To get the PR through we'd need to add a config for files which should be deleted when the app is removed ('zapped') from the system. Where do you store caches/configs/etc.? I'm not that familiar with Electron and also couldn't find anything in the code (I only took a brief look during my lunch break)

**Comment by roldanjr** [comment]
> Where do you store caches/configs/etc.?

I think we can get it using this line of code.

```javascript
const getAppPath = path.join(app.getPath('appData'), app.getName());

console.log(getAppPath); 

// I'm using Windows and I can confirm that the result is true but I'm not sure what exactly for the other OS.
// C:\Users\ROLDAN MONTILLA JR\AppData\Roaming\pomatez
```

![image](https://user-images.githubusercontent.com/38913069/98958218-08743b80-253d-11eb-83a9-02ce45ca823e.png)

**Comment by cabbage** [comment]
Ah thanks, found the macOS equivalent here: `~/Library/Application Support/pomatez`

I updated the PR.

**Comment by roldanjr** [comment]
Thanks @cabbage for helping. 😀

**Comment by cabbage** [comment]
It's a pleasure to help :)

We just have to wait for the Homebrew-Cask maintainers to approve the PR.

**Comment by roldanjr** [comment]
Thanks @cabbage .
